version: '3'

services:
  search:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.1
    environment:
      - cluster.name=fusionauth
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
# Un-comment to access the search service directly
    ports:
      - 9200:9200
    networks:
      - nginx-proxy
    restart: unless-stopped
    container_name: search
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data

  fusionauth:
    image: fusionauth/fusionauth-app:latest
    depends_on:
      - search
    environment:
      VIRTUAL_HOST: auth.yourdomain.com
      VIRTUAL_PORT: 9011
      DATABASE_URL: jdbc:mysql://mysql_db:3306/fusionauth_db?serverTimezone=UTC
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      FUSIONAUTH_MEMORY: ${FUSIONAUTH_MEMORY}
      FUSIONAUTH_SEARCH_SERVERS: http://search:9200
      FUSIONAUTH_URL: http://fusionauth:9011
    networks:
     - nginx-proxy
    restart: unless-stopped
    container_name: fusionauth 
    ports:
      - 9011:9011
    volumes:
      - fa_config:/usr/local/fusionauth/config

volumes:
  es_data:
  fa_config:

networks:
  nginx-proxy:
    external: true
