
version: "3"

services:
   mysql_node:
     image: mysql:5.7.29
     volumes:
       - mysql_db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: YourRootPassword
     container_name: mysql_db
     ports:
      - "3306:3306"
     command: '--default-authentication-plugin=mysql_native_password'
     networks:
       - nginx-proxy
volumes:
    mysql_db_data:

networks:
  nginx-proxy:
    external: true

