version: '3'

services:
   #Redis Service
   fuzonmediaredis:
     build:
      context: .
      dockerfile: Dockerfile
     image: fuzonmedia/redis
     restart: unless-stopped
     ports:
      - "6379:6379"
     volumes:
       - ./data/:/data
     container_name: fuzonmediaredis
     networks:
       - nginx-proxy

networks:
  nginx-proxy:
    external: true



